# Generated by Django 5.1.1 on 2024-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('dob', models.DateField()),
                ('passport', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('startDate', models.TextField()),
                ('endDate', models.TextField()),
                ('adults', models.CharField(max_length=100)),
                ('children', models.CharField(max_length=100)),
                ('typeTrip', models.CharField(max_length=100)),
                ('specialRequests', models.TextField()),
                ('roomType', models.CharField(max_length=100)),
                ('add_services', models.CharField(choices=[('yes', 'Travel Insurance'), ('yes', 'Air Pickup'), ('yes', 'Guided Tours')], max_length=100)),
                ('customExperience', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(choices=[('credit', 'Credit/Debit Card'), ('paypal', 'PayPal')], max_length=100)),
                ('cardName', models.CharField(max_length=100)),
                ('expiry', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('billingAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
